yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import F, Q
from django.db.models.constraints import CheckConstraint, UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200,
                             verbose_name='Название группы',
                             help_text='Введите название группы'
                             )
    slug = models.SlugField(unique=True,
                            verbose_name='Адрес группы',
                            help_text='Желаемый адрес группы'
                            )
    description = models.TextField(verbose_name='Описание группы',
                                   help_text='Введите описание группы'
                                   )

    class Meta:
        verbose_name = 'Жанр'
        verbose_name_plural = 'Жанры'
        ordering = ('title',)

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    POST_TEXT_LEN = 15
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        help_text='Группа, в которой будет этот пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['-pub_date']
        default_related_name = 'posts'

    def __str__(self) -> str:
        return self.text[:Post.POST_TEXT_LEN]


class Comment(models.Model):
    COMMENT_TEXT_LEN = 15
    post = models.ForeignKey(
        Post,
        related_name='comments',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Текст поста',
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Автор',
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self) -> str:
        return self.text[:Comment.COMMENT_TEXT_LEN]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
    )

    class Meta:
        constraints = [
            CheckConstraint(check=~Q(user=F('author')),
                            name='could_not_follow_itself'),
            UniqueConstraint(fields=['user', 'author'], name='unique_follower')
        ]
        verbose_name = 'подписка'
        verbose_name_plural = 'подписки'

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        help_text = {'text': 'Текст поста',
                     'group': 'Группа',
                     'image': 'Изображение'}
        label = {'text': 'Введите текст',
                 'group': 'Выберите группу',
                 'image': 'Добавьте картинку'}


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator_utils


def index(request):
    context = {
        'page_obj': paginator_utils(
            Post.objects.select_related('author', 'group'), request)
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    context = {
        'group': group,
        'page_obj': paginator_utils(posts, request)
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = (request.user.is_authenticated
                 and Follow.objects.filter(user=request.user,
                                           author=author).exists())
    context = {
        'author': author,
        'page_obj': paginator_utils(
            author.posts.select_related('author'), request),
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    context = {'post': post,
               'form': CommentForm()}
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST,
        files=request.FILES or None
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post.id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if not form.is_valid():
        return render(request, 'posts/create_post.html',
                      {'form': form, 'post': post})
    post = form.save()
    return redirect('posts:post_detail', post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    context = {'page_obj': paginator_utils(Post.objects.filter(
        author__following__user=request.user), request)}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(Follow, user=request.user,
                      author__username=username).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  Новый пост
{% endblock title %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if post %}Редактировать пост{% else %}Добавить пост{% endif %}
          </div>
          {% include 'includes/form.html' %}
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Посты автора, на которого Вы подписаны
{% endblock title %}
{% block content %}
  {% cache 20 index_page %}
    <div class="container py-5">
      <h1>Посты автора</h1>
      {% include 'posts/includes/switcher.html' with follow=True %}
      {% for post in page_obj %}
        {% include 'includes/single_post.html' %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group }}"</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endcache %}
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock title %}
{% block content %}
  <div class="container">
    <h1> {{ group.title }} </h1>
    <p> {{ group.description|linebreaks }} </p>
    {% for post in page_obj %}
      {% include 'includes/single_post.html' %}
      {% if not forloop.last %}
        <hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock title %}
{% block content %}
  {% cache 1 index_page %}
    <div class="container py-5">
      <h1>Последние обновления на сайте</h1>
      {% include 'posts/includes/switcher.html' with follow=False index=True %}
      {% for post in page_obj %}
        {% include 'includes/single_post.html' %}
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group }}"</a>
        {% endif %}
        {% if not forloop.last %}
          <hr>{% endif %}
      {% endfor %}
      {% include 'posts/includes/paginator.html' %}
    </div>
  {% endcache %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock title %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group }}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора: <span>{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text|linebreaksbr }}
      </p>
      {% if post.author == request.user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          редактировать запись
        </a>
      {% endif %}
      {% include 'includes/comment.html' %}
    </article>
  </div>
  </div>
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock title %}
{% block content %}
  <div class="mb-5">
    <h1>Все посты пользователя {{ author.get_full_name }}</h1>
    <ul>
      <li>Всего постов: {{ author.posts.count }}</li>
      <li>Всего комментариев: {{ author.comments.count }}</li>
      <li>Количество подписчиков: {{ author.following.count }}</li>
      <li>Колличество подписок: {{ author.follower.count }}</li>
    </ul>
    {% if user.is_authenticated and author != user %}
      {% if following %}
        <a class="btn btn-lg btn-light"
           href="{% url 'posts:profile_unfollow' author.username %}"
           role="button">Отписаться</a>
      {% else %}
        <a class="btn btn-lg btn-primary"
           href="{% url 'posts:profile_follow' author.username %}"
           role="button">Подписаться</a>
      {% endif %}
    {% endif %}
  </div>
  {% for post in page_obj %}
    <article>
      {% include 'includes/single_post.html' %}
    </article>
    {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group }}"</a>
    {% endif %}
    {% if not forloop.last %}
      <hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock content %}